
services:
  selenium-hub:
    image: selenium/hub:4.8.0
    container_name: selenium-hub
    networks:
      - mynetwork
    ports:
      - "4444:4444"

  chrome:
    image: selenium/node-chrome:4.8.0
    depends_on:
      - selenium-hub
    networks:
      - mynetwork
    environment:
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443

  firefox:
    image: selenium/node-firefox:4.8.0
    depends_on:
      - selenium-hub
    networks:
      - mynetwork
    environment:
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443

  mysql:
    image: mysql:8.0
    container_name: mysql
    restart: always
    networks:
      - mynetwork
    environment:
      MYSQL_ROOT_PASSWORD: rootpwd
      MYSQL_DATABASE: testdb
      MYSQL_USER: testuser
      MYSQL_PASSWORD: testpwd
    ports:
      - "3306:3306"

  test-runner:
    build:
      context: .
      dockerfile: Dockerfile
    image: my-test-automation
    networks:
      - mynetwork
    environment:
      SELENIUM_HUB_URL: "http://selenium-hub:4444/wd/hub"
      DB_URL: "jdbc:mysql://mysql:3306/testdb"
      DB_USER: "testuser"
      DB_PASSWORD: "testpwd"
    depends_on:
      - selenium-hub
      - mysql
    volumes:
      - ./target/screenshots:/app/target/screenshots

networks:
  mynetwork:
